name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,cpp,h} | xargs clang-format -i && git diff --exit-code

      - name: Build application
        run: make

      - name: Tests
        run: make test
      
      - name: Run tests
        run: ./bin/test
